from .generator import PPTGenerator
from .suggestor import Suggestor

def main():
    import argparse
    parser = argparse.ArgumentParser(description="PPT Architect: Create, Analyze, and Suggest PPTs")
    parser.add_argument("--topic", type=str, help="Topic for the presentation", default="AI in Engineering")
    parser.add_argument("--output", type=str, help="Output filename", default="presentation.pptx")
    
    args = parser.parse_args()

    print(f"Generating presentation for: {args.topic}")
    
    suggestor = Suggestor()
    outline = suggestor.suggest_outline(args.topic)
    
    gen = PPTGenerator(title=outline["title"])
    gen.add_title_slide(outline["title"], "Generated by PPT Architect")
    
    for slide in outline["slides"]:
        gen.add_content_slide(slide["title"], slide["content"])
    
    gen.save(args.output)

if __name__ == "__main__":
    main()